### ISSUE TITLE
Feature request: Delete confirmation

### ISSUE THREAD

**Issue by naanlizard** [vampirefrog/OvenMediaEngine-html-ui#1]
Hello, great work on this dash! I like it a lot, though the delete link not having a confirmation is scary. I'll take a stab at it myself probably when I have time, but figured I'd open a ticket first.

**Comment by vampirefrog** [comment]
I've added some JS confirm boxes (no time to use fancy Bootstrap ones instead), check it out and close the issue if you're happy with it.

**Comment by naanlizard** [comment]
Don't suppose you could upload a release?

Or tell me how to do it, can't say js is my forte but I'm sure I can figure it out

**Comment by vampirefrog** [comment]
I'm sorry, I forgot to mention that I  uploaded a release as well https://vampi.tech/demos/ome-client

**Comment by naanlizard** [comment]
Ah, I meant on github - due to how I've got OME running, it's tricky to use an admin panel hosted elsewhere

**Comment by vampirefrog** [comment]
Ok [try it out](https://github.com/vampirefrog/OvenMediaEngine-html-ui/releases/tag/v0.3a).

**Comment by naanlizard** [comment]
Great addition, tested deleting a stream and it was exactly what was needed
