### ISSUE TITLE
Reload certs button

### ISSUE THREAD

**Issue by naanlizard** [vampirefrog/OvenMediaEngine-html-ui#4]
Reloading the certs via the admin panel would be useful from time to time, as would showing the actual cert file content if we can get it

https://github.com/AirenSoft/OvenMediaEngine/discussions/1084

**Comment by vampirefrog** [comment]
Check new release

**Comment by vampirefrog** [comment]
I've also added developer instructions (easy) to the [README](https://github.com/vampirefrog/OvenMediaEngine-html-ui/blob/master/README.md) if you want to run it locally.
